version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-flask-songs-kata
    volumes:
      - ".:/app"
    ports:
      - "5001:5000"
    tty: true